# Feature Selection

## Import Libraries

In [106]:
import pandas as pd
import numpy as np

## Load  Data

In [107]:
df = pd.read_csv("../data/processed/feature_engineered_complaints.csv")

## View Data

In [108]:
df.head()

,complaint_id,citizen_id,category,sub_category,ward,reported_date,status,people_affected,vulnerable_population,public_safety_risk,recurrence_indicator,severity,vulnerable_population_ratio,complaint_age_days,is_active_complaint,ward_complaint_load
0,C000001,P0869,Drainage,Drain Blockage,Peenya,2025-10-01,Closed,230.0,39.0,Medium,No,High,0.169565,0,False,25
1,C000002,P0993,Sewerage,Sewage Overflow,Hennur,2025-10-01,Resolved,70.0,14.0,Critical,No,Medium,0.200000,0,False,8
2,C000003,P1709,Street Infrastructure,Fallen Tree Branch,Dasarahalli,2025-10-01,Closed,190.0,12.0,Medium,No,Medium,0.063158,0,False,67
3,C000004,P1458,Revenue Department,Trade Licence Issue,Chickpet,2025-10-01,Resolved,7.0,2.0,Low,No,Low,0.285714,0,False,10
4,C000005,P1565,Water Supply,No Water Supply,Vasanthnagar,2025-10-01,Closed,140.0,21.0,Low,No,High,0.150000,0,False,7

In [109]:
df.shape

(8953, 16)

In [110]:
df.columns

Index(['complaint_id', 'citizen_id', 'category', 'sub_category', 'ward',
       'reported_date', 'status', 'people_affected', 'vulnerable_population',
       'public_safety_risk', 'recurrence_indicator', 'severity',
       'vulnerable_population_ratio', 'complaint_age_days',
       'is_active_complaint', 'ward_complaint_load'],
      dtype='str')

In [111]:
df.dtypes

complaint_id                       str
citizen_id                         str
category                           str
sub_category                       str
ward                               str
reported_date                      str
status                             str
people_affected                float64
vulnerable_population          float64
public_safety_risk                 str
recurrence_indicator               str
severity                           str
vulnerable_population_ratio    float64
complaint_age_days               int64
is_active_complaint               bool
ward_complaint_load              int64
dtype: object

## Target Variable

In [112]:
target = "severity"

print(df[target].unique())

<ArrowStringArray>
['High', 'Medium', 'Low', 'Critical']
Length: 4, dtype: str

In [113]:
print("Severity distribution:")
display(df[target].value_counts())

Severity distribution:

severity
Medium      3530
Low         2710
High        2000
Critical     713
Name: count, dtype: int64

In [114]:
print("\nSeverity distribution in percentage:")
display(
    (df[target].value_counts(normalize=True) * 100)
    .round(2)
)

Severity distribution in percentage:

severity
Medium      39.43
Low         30.27
High        22.34
Critical     7.96
Name: proportion, dtype: float64

## Separate Features and Target

In [115]:
X = df.drop(columns=[target])
Y = df[target]

In [116]:
print("Features shape:", X.shape)
print("Target shape:", Y.shape)

Features shape: (8953, 15)
Target shape: (8953,)

In [117]:
print("\nTarget classes:")
print(sorted(Y.unique()))

Target classes:
['Critical', 'High', 'Low', 'Medium']

## Columns for ML Training

In [118]:
columns_to_exclude = [
    "complaint_id",
    "citizen_id",
    "ward",
    "reported_date",
    "status",
    "complaint_age_days",
    "is_active_complaint",
    "ward_complaint_load",
]

In [119]:
columns_to_exclude = [
    col for col in columns_to_exclude
    if col in X.columns
]

X = X.drop(columns=columns_to_exclude)

In [120]:
print("Excluded columns:", columns_to_exclude)
print("\nRemaining feature columns:")
print(X.columns)

Excluded columns: ['complaint_id', 'citizen_id', 'ward', 'reported_date', 'status', 'complaint_age_days', 'is_active_complaint', 'ward_complaint_load']

Remaining feature columns:
Index(['category', 'sub_category', 'people_affected', 'vulnerable_population',
       'public_safety_risk', 'recurrence_indicator',
       'vulnerable_population_ratio'],
      dtype='str')

## Veiw Selected Features

In [121]:
X.head()

,category,sub_category,people_affected,vulnerable_population,public_safety_risk,recurrence_indicator,vulnerable_population_ratio
0,Drainage,Drain Blockage,230.0,39.0,Medium,No,0.169565
1,Sewerage,Sewage Overflow,70.0,14.0,Critical,No,0.200000
2,Street Infrastructure,Fallen Tree Branch,190.0,12.0,Medium,No,0.063158
3,Revenue Department,Trade Licence Issue,7.0,2.0,Low,No,0.285714
4,Water Supply,No Water Supply,140.0,21.0,Low,No,0.150000

In [122]:
X.shape

(8953, 7)

In [123]:
X.dtypes

category                           str
sub_category                       str
people_affected                float64
vulnerable_population          float64
public_safety_risk                 str
recurrence_indicator               str
vulnerable_population_ratio    float64
dtype: object

In [124]:
Y.head()

0      High
1    Medium
2    Medium
3       Low
4      High
Name: severity, dtype: str

## Categorical Features

In [125]:
categorical_features = X.select_dtypes(
    include=["object", "category", "str"]
).columns

for col in categorical_features:
    print(f"\n{col} by severity:")
    display(pd.crosstab(df[col], Y, normalize="index").round(2))

category by severity:

severity                Critical  High   Low  Medium
category
Drainage                    0.09  0.31  0.21    0.39
Electrical                  0.07  0.28  0.22    0.44
Health                      0.08  0.31  0.19    0.42
Others                      0.00  0.04  0.77    0.19
Public Sanitation           0.03  0.15  0.47    0.35
Revenue Department          0.00  0.00  0.98    0.02
Road Infrastructure         0.04  0.19  0.34    0.43
Road Maintenance            0.06  0.25  0.28    0.42
Sewerage                    0.21  0.30  0.10    0.40
Solid Waste Management      0.02  0.12  0.45    0.41
Street Infrastructure       0.03  0.19  0.35    0.43
Water Supply                0.24  0.31  0.10    0.35

sub_category by severity:

severity                            Critical  High   Low  Medium
sub_category
Bus Shelter Damaged                     0.02  0.12  0.34    0.52
Damaged Drain                           0.03  0.18  0.30    0.48
Damaged Footpath Railing                0.02  0.23  0.33    0.42
Damaged Signboard                       0.00  0.05  0.56    0.40
Damaged Street Light                    0.04  0.22  0.25    0.49
Drain Blockage                          0.07  0.28  0.27    0.37
Drain Overflow                          0.14  0.34  0.14    0.38
Electric Pole Damaged                   0.07  0.43  0.11    0.39
Exposed Electrical Wires                0.06  0.48  0.09    0.36
Fallen Tree Branch                      0.08  0.31  0.23    0.38
Footpath Damage                         0.00  0.16  0.34    0.51
Garbage Burning                         0.06  0.20  0.25    0.49
Garbage Dump                            0.00  0.11  0.46    0.43
Garbage Dumping in Vacant Site          0.01  0.09  0.57    0.33
Garbage Not Collected                   0.03  0.15  0.42    0.40
Garbage Vehicle Not Arrived             0.01  0.12  0.43    0.44
Illegal Construction                    0.00  0.12  0.64    0.24
Increase in Mosquito Density            0.08  0.36  0.12    0.43
Khata Related Issue                     0.00  0.00  0.96    0.04
Low Water Pressure                      0.04  0.15  0.31    0.50
Manhole Overflow                        0.16  0.41  0.13    0.30
Miscellaneous Complaint                 0.00  0.02  0.86    0.12
Missing Manhole Cover                   0.09  0.19  0.19    0.53
Multiple Street Lights Not Working      0.15  0.38  0.10    0.37
No Water Supply                         0.28  0.39  0.03    0.30
Open Drain                              0.04  0.42  0.19    0.35
Pipeline Leakage                        0.29  0.27  0.09    0.35
Pothole                                 0.09  0.24  0.24    0.43
Property Tax Query                      0.00  0.00  0.97    0.03
Public Health Sanitation Issue          0.04  0.28  0.23    0.45
Public Toilet Not Maintained            0.04  0.17  0.44    0.36
Road Cutting Not Restored               0.03  0.18  0.32    0.46
Road Encroachment                       0.01  0.17  0.49    0.33
Road Maintenance Required               0.02  0.21  0.46    0.31
Road Signage Missing                    0.00  0.12  0.44    0.44
Road Surface Damage                     0.05  0.38  0.20    0.36
Sewage Overflow                         0.29  0.34  0.07    0.30
Sewer Line Blockage                     0.11  0.21  0.10    0.57
Speed Breaker Required                  0.05  0.28  0.26    0.41
Stray Cattle on Road                    0.00  0.00  0.71    0.29
Stray Dog Menace                        0.13  0.25  0.27    0.35
Street Light Not Working                0.02  0.18  0.32    0.49
Sweeping Not Done                       0.01  0.06  0.53    0.39
Trade Licence Issue                     0.00  0.00  1.00    0.00
Unclean Public Area                     0.00  0.08  0.68    0.23
Water Leakage                           0.16  0.25  0.21    0.39
exposed electrical wires                0.00  0.00  0.00    1.00
garbage not collected                   0.00  0.00  1.00    0.00
garbage vehicle not arrived             0.00  0.00  1.00    0.00
manhole overflow                        0.50  0.00  0.00    0.50
multiple street lights not working      0.00  0.00  1.00    0.00
no water supply                         0.00  0.50  0.00    0.50
open drain                              0.00  0.00  0.00    1.00
pipeline leakage                        1.00  0.00  0.00    0.00
pothole                                 0.00  0.50  0.00    0.50
public health sanitation issue          0.00  1.00  0.00    0.00
sewer line blockage                     0.00  0.00  0.00    1.00
stray cattle on road                    0.00  0.00  0.00    1.00
water leakage                           0.00  0.00  1.00    0.00

public_safety_risk by severity:

severity            Critical  High   Low  Medium
public_safety_risk
Critical                0.40  0.46  0.01    0.14
High                    0.23  0.42  0.04    0.30
Low                     0.01  0.10  0.50    0.40
Medium                  0.05  0.29  0.16    0.49

recurrence_indicator by severity:

severity              Critical  High   Low  Medium
recurrence_indicator
No                        0.07  0.21  0.32    0.40
Yes                       0.09  0.24  0.29    0.38

## Save Data

In [126]:
ml_ready_df = X.copy()
ml_ready_df["severity"] = Y

In [130]:
ml_ready_df.to_csv("../data/processed/ml_ready_complaints.csv", index=False)

In [129]:
ml_ready_df.head()

,category,sub_category,people_affected,vulnerable_population,public_safety_risk,recurrence_indicator,vulnerable_population_ratio,severity
0,Drainage,Drain Blockage,230.0,39.0,Medium,No,0.169565,High
1,Sewerage,Sewage Overflow,70.0,14.0,Critical,No,0.200000,Medium
2,Street Infrastructure,Fallen Tree Branch,190.0,12.0,Medium,No,0.063158,Medium
3,Revenue Department,Trade Licence Issue,7.0,2.0,Low,No,0.285714,Low
4,Water Supply,No Water Supply,140.0,21.0,Low,No,0.150000,High